import type pg from "pg";

type PrivilegeClient = Pick<pg.Client, "query">;

type PrivilegeProbeOptions = {
  migrationClient: PrivilegeClient;
  migrationRole: string;
  runtimeClient: PrivilegeClient;
};

export type DatabasePrivilegeContract = {
  migrationCanCreateAndAlter: boolean;
  migrationCanCreateRole: boolean;
  migrationIsSuperuser: boolean;
  runtimeAlterSqlState: string;
  runtimeAssumeMigrationRoleSqlState: string;
  runtimeCanConnect: boolean;
  runtimeCanDeleteFutureRows: boolean;
  runtimeCanInsertFutureRows: boolean;
  runtimeCanSelectFutureRows: boolean;
  runtimeCanUpdateFutureRows: boolean;
  runtimeCanUseFutureSequence: boolean;
  runtimeCanUseSchema: boolean;
  runtimeCreateSqlState: string;
  runtimeDropSqlState: string;
  runtimeHasCurrentTableDml: boolean;
  runtimeTemporaryCreateSqlState: string;
};

type CapabilityRow = {
  can_connect: boolean;
  has_current_table_dml: boolean;
  can_use_future_sequence: boolean;
  can_use_schema: boolean;
};

type MigrationRoleRow = {
  can_create_role: boolean;
  is_superuser: boolean;
};

const futureTable = "privilege_probe_future";
const forbiddenTable = "forbidden_runtime_ddl";
const forbiddenTemporaryTable = "forbidden_runtime_temporary_ddl";

export async function probeDatabasePrivileges({
  migrationClient,
  migrationRole,
  runtimeClient,
}: PrivilegeProbeOptions): Promise<DatabasePrivilegeContract> {
  let migrationCanCreateAndAlter = false;

  try {
    const migrationRoleCapabilities =
      await migrationClient.query<MigrationRoleRow>(`
        SELECT
          rolcreaterole AS can_create_role,
          rolsuper AS is_superuser
        FROM pg_catalog.pg_roles
        WHERE rolname = current_user
      `);
    await migrationClient.query(`
      CREATE TABLE ${futureTable} (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        value TEXT NOT NULL
      )
    `);
    await migrationClient.query(`
      ALTER TABLE ${futureTable}
      ADD COLUMN created_by TEXT NOT NULL DEFAULT 'migration'
    `);
    migrationCanCreateAndAlter = true;

    const capabilities = await runtimeClient.query<CapabilityRow>(`
      SELECT
        has_database_privilege(
          current_user,
          current_database(),
          'CONNECT'
        ) AS can_connect,
        has_schema_privilege(
          current_user,
          'public',
          'USAGE'
        ) AS can_use_schema,
        (
          SELECT bool_and(
            has_table_privilege(
              current_user,
              format('%I.%I', table_schema, table_name),
              'SELECT'
            )
            AND has_table_privilege(
              current_user,
              format('%I.%I', table_schema, table_name),
              'INSERT'
            )
            AND has_table_privilege(
              current_user,
              format('%I.%I', table_schema, table_name),
              'UPDATE'
            )
            AND has_table_privilege(
              current_user,
              format('%I.%I', table_schema, table_name),
              'DELETE'
            )
          )
          FROM information_schema.tables
          WHERE table_schema = 'public'
            AND table_type = 'BASE TABLE'
        ) AS has_current_table_dml,
        has_sequence_privilege(
          current_user,
          'public.privilege_probe_future_id_seq',
          'USAGE'
        ) AS can_use_future_sequence
    `);

    const inserted = await runtimeClient.query<{ id: string }>(`
      INSERT INTO ${futureTable} (value)
      VALUES ('created by runtime')
      RETURNING id
    `);
    const insertedId = inserted.rows[0]?.id;
    const selected = await runtimeClient.query<{ value: string }>(
      `SELECT value FROM ${futureTable} WHERE id = $1`,
      [insertedId],
    );
    const updated = await runtimeClient.query(
      `UPDATE ${futureTable} SET value = 'updated by runtime' WHERE id = $1`,
      [insertedId],
    );
    const deleted = await runtimeClient.query(
      `DELETE FROM ${futureTable} WHERE id = $1`,
      [insertedId],
    );

    const runtimeCreateSqlState = await deniedSqlState(
      runtimeClient,
      `CREATE TABLE ${forbiddenTable} (id INTEGER)`,
    );
    const runtimeAlterSqlState = await deniedSqlState(
      runtimeClient,
      `ALTER TABLE ${futureTable} ADD COLUMN forbidden INTEGER`,
    );
    const runtimeDropSqlState = await deniedSqlState(
      runtimeClient,
      `DROP TABLE ${futureTable}`,
    );
    const runtimeTemporaryCreateSqlState = await deniedSqlState(
      runtimeClient,
      `CREATE TEMPORARY TABLE ${forbiddenTemporaryTable} (id INTEGER)`,
    );
    if (runtimeTemporaryCreateSqlState === "ALLOWED") {
      await runtimeClient.query(`DROP TABLE ${forbiddenTemporaryTable}`);
    }
    const runtimeAssumeMigrationRoleSqlState = await deniedSqlState(
      runtimeClient,
      `SET ROLE ${quoteIdentifier(migrationRole)}`,
    );
    if (runtimeAssumeMigrationRoleSqlState === "ALLOWED") {
      await runtimeClient.query("RESET ROLE");
    }

    const capability = capabilities.rows[0];
    if (!capability) {
      throw new Error("The runtime privilege query returned no result");
    }
    const migrationCapability = migrationRoleCapabilities.rows[0];
    if (!migrationCapability) {
      throw new Error("The migration role query returned no result");
    }

    return {
      migrationCanCreateAndAlter,
      migrationCanCreateRole: migrationCapability.can_create_role,
      migrationIsSuperuser: migrationCapability.is_superuser,
      runtimeAlterSqlState,
      runtimeAssumeMigrationRoleSqlState,
      runtimeCanConnect: capability.can_connect,
      runtimeCanDeleteFutureRows: deleted.rowCount === 1,
      runtimeCanInsertFutureRows: insertedId !== undefined,
      runtimeCanSelectFutureRows:
        selected.rows[0]?.value === "created by runtime",
      runtimeCanUpdateFutureRows: updated.rowCount === 1,
      runtimeCanUseFutureSequence: capability.can_use_future_sequence,
      runtimeCanUseSchema: capability.can_use_schema,
      runtimeCreateSqlState,
      runtimeDropSqlState,
      runtimeHasCurrentTableDml: capability.has_current_table_dml,
      runtimeTemporaryCreateSqlState,
    };
  } finally {
    await migrationClient.query(`DROP TABLE IF EXISTS ${forbiddenTable}`);
    await migrationClient.query(`DROP TABLE IF EXISTS ${futureTable}`);
  }
}

async function deniedSqlState(
  client: PrivilegeClient,
  statement: string,
): Promise<string> {
  try {
    await client.query(statement);
    return "ALLOWED";
  } catch (error) {
    if (
      typeof error === "object" &&
      error !== null &&
      "code" in error &&
      typeof error.code === "string"
    ) {
      return error.code;
    }
    throw error;
  }
}

function quoteIdentifier(identifier: string): string {
  return `"${identifier.replaceAll('"', '""')}"`;
}
