apiVersion: v1
kind: ConfigMap
metadata:
  name: primeiro-prontuario-config
  namespace: primeiro-prontuario
data:
  APP_TIME_ZONE: America/Sao_Paulo
  ATTACHMENT_STORAGE_DIRECTORY: /var/lib/primeiro-prontuario/attachments/application
  SESSION_COOKIE_SECURE: "true"
  SESSION_TIMEOUT: 30m
  SPRING_DATASOURCE_HIKARI_DATA_SOURCE_PROPERTIES_SSLMODE: require
  SPRING_PROFILES_ACTIVE: prod
  TRUSTED_PROXY_NETWORKS: '10\.\d{1,3}\.\d{1,3}\.\d{1,3}|172\.(1[6-9]|2\d|3[0-1])\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}'
