apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: primeiro-prontuario-attachments
  namespace: primeiro-prontuario
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
