package br.com.primeiroprontuario.audit;

public enum AuditAction {
    AUTH_LOGIN_SUCCEEDED,
    AUTH_LOGIN_FAILED,
    AUTH_LOGOUT,
    PATIENT_CREATED,
    PATIENT_UPDATED,
    PATIENT_STATUS_CHANGED,
    APPOINTMENT_CREATED,
    APPOINTMENT_RESCHEDULED,
    APPOINTMENT_STATUS_CHANGED,
    SCHEDULE_BLOCK_CREATED,
    SCHEDULE_BLOCK_REMOVED,
    CONSULTATION_FINALIZED,
    ADDENDUM_ADDED,
    MEDICAL_RECORD_VIEWED,
    ATTACHMENT_UPLOADED,
    ATTACHMENT_DOWNLOADED,
    ATTACHMENT_REMOVED
}
